version: '3.8'

services:
  shifaai:
    build: .
    container_name: shifaai-app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - MAX_RESPONSE_LENGTH=2000
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - shifaai-network

  # Optional: Redis for caching (for future enhancement)
  redis:
    image: redis:7-alpine
    container_name: shifaai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - shifaai-network

  # Optional: Nginx reverse proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: shifaai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - shifaai
    restart: unless-stopped
    networks:
      - shifaai-network

volumes:
  redis_data:

networks:
  shifaai-network:
    driver: bridge 